// Generated by scripts/codex-bindings.mjs. Do not edit by hand.
export const generatedCodexBindingManifest = {
  "schemaVersion": 1,
  "codexVersion": "0.148.0",
  "experimentalApi": true,
  "generationArgs": [
    "app-server",
    "generate-ts",
    "--experimental",
    "--out"
  ],
  "fileCount": 752,
  "treeSha256": "0aea36ac0450f592831cff6df4c9e09fc2fd46ad37f6ed7a520d6f1cc59130d9",
  "bindingId": "codex-app-server-0.148.0-experimental:sha256:0aea36ac0450f592831cff6df4c9e09fc2fd46ad37f6ed7a520d6f1cc59130d9"
} as const;
