// Generated by scripts/codex-bindings.mjs. Do not edit by hand.
export const generatedCodexBindingManifest = {
  "schemaVersion": 1,
  "codexVersion": "0.147.0",
  "experimentalApi": true,
  "generationArgs": [
    "app-server",
    "generate-ts",
    "--experimental",
    "--out"
  ],
  "fileCount": 723,
  "treeSha256": "673c02b5a758e082cb02c15f36bf4f37e88501470fd430ad232bebd754e8689c",
  "bindingId": "codex-app-server-0.147.0-experimental:sha256:673c02b5a758e082cb02c15f36bf4f37e88501470fd430ad232bebd754e8689c"
} as const;
